---
repos:
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.39.0
      hooks:
          - id: markdownlint
    -   repo: https://github.com/shellcheck-py/shellcheck-py
        rev: v0.10.0.1
        hooks:
            - id: shellcheck